# Generated by Django 3.0.3 on 2020-03-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('detail', models.CharField(max_length=2048)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAct', models.DateTimeField(null=True)),
            ],
        ),
    ]
