# Generated by Django 3.0.3 on 2020-03-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200305_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['createdAt']},
        ),
    ]
